### ISSUE TITLE
Separate Migrations Assembly Issue

### ISSUE THREAD

**Issue by mslattery** [bytefish/ModularEfCore#1]
First thanks for providing/supporting this project.

I was working on porting to mysql, and was having issues with the migrations being within a separate assembly.  So after some frustration I tried going back to the original source, cloned a new copy and lo and behold I experienced the same issue.

So here here is what I'm seeing when I try to add a new migration from this unmodified cloned repo.

#Cmd
dotnet ef migrations add test -v

#Error
Your target project 'ModularEfCore.Example.Web' doesn't match your migrations assembly 'ModularEfCore.Migrations'. Either change your target project or change your migrations assembly.
Change your migrations assembly by using DbContextOptionsBuilder. E.g. options.UseSqlServer(connection, b => b.MigrationsAssembly("ModularEfCore.Example.Web")). By default, the migrations assembly is the assembly containing the DbContext.
Change your target project to the migrations project by using the Package Manager Console's Default project drop-down list, or by executing "dotnet ef" from the directory containing the migrations project.

Details
C:\git\ModularEfCore-ORIG\ModularEfCore\ModularEfCore.Example.Web>dotnet ef migrations add test -v
Using project 'C:\git\ModularEfCore-ORIG\ModularEfCore\ModularEfCore.Example.Web\ModularEfCore.Example.Web.csproj'.
Using startup project 'C:\git\ModularEfCore-ORIG\ModularEfCore\ModularEfCore.Example.Web\ModularEfCore.Example.Web.csproj'.
Writing 'C:\git\ModularEfCore-ORIG\ModularEfCore\ModularEfCore.Example.Web\obj\ModularEfCore.Example.Web.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\mslattery\AppData\Local\Temp\1\tmpF953.tmp /verbosity:quiet /nologo C:\git\ModularEfCore-ORIG\ModularEfCore\ModularEfCore.Example.Web\ModularEfCore.Example.Web.csproj
Writing 'C:\git\ModularEfCore-ORIG\ModularEfCore\ModularEfCore.Example.Web\obj\ModularEfCore.Example.Web.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\mslattery\AppData\Local\Temp\1\tmpFF7F.tmp /verbosity:quiet /nologo C:\git\ModularEfCore-ORIG\ModularEfCore\ModularEfCore.Example.Web\ModularEfCore.Example.Web.csproj
dotnet build C:\git\ModularEfCore-ORIG\ModularEfCore\ModularEfCore.Example.Web\ModularEfCore.Example.Web.csproj /verbosity:quiet /nologo

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.96
dotnet exec --depsfile C:\git\ModularEfCore-ORIG\ModularEfCore\ModularEfCore.Example.Web\bin\Debug\netcoreapp2.1\ModularEfCore.Example.Web.deps.json --additionalprobingpath C:\Users\mslattery\.nuget\packages --additionalprobingpath "C:\Program Files\dotnet\sdk\NuGetFallbackFolder" --runtimeconfig C:\git\ModularEfCore-ORIG\ModularEfCore\ModularEfCore.Example.Web\bin\Debug\netcoreapp2.1\ModularEfCore.Example.Web.runtimeconfig.json "C:\Program Files\dotnet\sdk\2.1.402\DotnetTools\dotnet-ef\2.1.3\tools\netcoreapp2.1\any\tools\netcoreapp2.0\any\ef.dll" migrations add test --assembly C:\git\ModularEfCore-ORIG\ModularEfCore\ModularEfCore.Example.Web\bin\Debug\netcoreapp2.1\ModularEfCore.Example.Web.dll --startup-assembly C:\git\ModularEfCore-ORIG\ModularEfCore\ModularEfCore.Example.Web\bin\Debug\netcoreapp2.1\ModularEfCore.Example.Web.dll --project-dir C:\git\ModularEfCore-ORIG\ModularEfCore\ModularEfCore.Example.Web\ --language C# --working-dir C:\git\ModularEfCore-ORIG\ModularEfCore\ModularEfCore.Example.Web --verbose --root-namespace ModularEfCore.Example.Web
Using assembly 'ModularEfCore.Example.Web'.
Using startup assembly 'ModularEfCore.Example.Web'.
Using application base 'C:\git\ModularEfCore-ORIG\ModularEfCore\ModularEfCore.Example.Web\bin\Debug\netcoreapp2.1'.
Using working directory 'C:\git\ModularEfCore-ORIG\ModularEfCore\ModularEfCore.Example.Web'.
Using root namespace 'ModularEfCore.Example.Web'.
Using project directory 'C:\git\ModularEfCore-ORIG\ModularEfCore\ModularEfCore.Example.Web\'.
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Finding application service provider...
Finding IWebHost accessor...
Using environment 'Development'.
Using application service provider from IWebHost accessor on 'Program'.
Found DbContext 'ApplicationDbContext'.
Finding DbContext classes in the project...
Using context 'ApplicationDbContext'.
Finding design-time services for provider 'Microsoft.EntityFrameworkCore.SqlServer'...
Using design-time services from provider 'Microsoft.EntityFrameworkCore.SqlServer'.
Finding design-time services referenced by assembly 'ModularEfCore.Example.Web'.
No referenced design-time services were found.
Finding IDesignTimeServices implementations in assembly 'ModularEfCore.Example.Web'...
No design-time services were found.
'ApplicationDbContext' disposed.
Microsoft.EntityFrameworkCore.Design.OperationException: Your target project 'ModularEfCore.Example.Web' doesn't match your migrations assembly 'ModularEfCore.Migrations'. Either change your target project or change your migrations assembly.
Change your migrations assembly by using DbContextOptionsBuilder. E.g. options.UseSqlServer(connection, b => b.MigrationsAssembly("ModularEfCore.Example.Web")). By default, the migrations assembly is the assembly containing the DbContext.
Change your target project to the migrations project by using the Package Manager Console's Default project drop-down list, or by executing "dotnet ef" from the directory containing the migrations project.
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.EnsureMigrationsAssembly(IServiceProvider services)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Your target project 'ModularEfCore.Example.Web' doesn't match your migrations assembly 'ModularEfCore.Migrations'. Either change your target project or change your migrations assembly.
Change your migrations assembly by using DbContextOptionsBuilder. E.g. options.UseSqlServer(connection, b => b.MigrationsAssembly("ModularEfCore.Example.Web")). By default, the migrations assembly is the assembly containing the DbContext.
Change your target project to the migrations project by using the Package Manager Console's Default project drop-down list, or by executing "dotnet ef" from the directory containing the migrations project.

**Comment by mslattery** [comment]
FYI - I was able to solve by providing the --startup-project parameter.

Run from the migrations assembly directory.

dotnet ef migrations add --startup-project ..\NextPMO.WebAPI.HR.Employee Test

**Comment by bytefish** [comment]
Accidentally I spent the entire day with Entity Framework database migrations and this is exactely what I wanted to say. 😅 Maybe you can do a Pull Request and add a little info to the README?

By the way, what do you think of the way to build EF Core applications the way I described it?
